[project]
name = "group-9"
version = "0.1.0"
requires-python = ">=3.10"
description = "Add your description here"
readme = "README.md"
dependencies = ["plotly>=6.0.0", "scikit-learn>=1.4.0", "streamlit==1.42.0"]

[tool.poetry]
package-mode = false
